name: NestJS Build with Node.js 18

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint and format code
        run: |
          npm run lint
          npm run format
      - name: Build NestJS project
        run: npm run build --if-present
      - name: Run tests
        run: npm test
      - name: Push to Docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mrdali/e-commerce-back
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}